django-project/blog/urls.py
from django.urls import path
from . import views
from .views import create
app_name = 'blog'

urlpatterns = [
    path('create/' , views.create , name='create'),
    path('blog/create/', create, name='blog_create'),
    path('edit/<int:pk>/' , views.edit , name='edit'),
    path('<slug:slug>/' , views.detail , name='detail'),
]

django-project/blogsite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

import blog.views



urlpatterns = [
    path('' , blog.views.home , name="home"),
    path('blog/' , include('blog.urls')),
    path('account/' , include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('logout/', auth_views.LogoutView.as_view(), name='account_logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-project/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill


class Post(models.Model):
    title = models.CharField(default='' , max_length=255)
    body = models.TextField(default='' , blank=True)
    slug = models.SlugField(default='' , blank=True , max_length=255)
    date = models.DateTimeField(auto_now_add =True , null =True)
    updated = models.DateTimeField(auto_now = True , null = True)
    author = models.ForeignKey(User , null=True , blank=True , on_delete=models.CASCADE)
    image = models.ImageField(default='' , blank=True , upload_to='images')
    image_thumbnail = ImageSpecField(source='image' , processors=[ResizeToFill(700 , 150)], format='JPEG' , options={'quality':60})
    

    tags = TaggableManager


    def __str__(self):
        return self.title
    
    def save(self , *args , **kwargs):
        self.slug = slugify(self.title)
        super().save(*args , **kwargs)  

    def get_absolute_url(self):
        return reverse('blog:detail' , args=[str(self.slug)])
    

django-project/blog/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title' , 'body' , 'slug' , 'image']

django-project/blog/views.py
from ctypes.wintypes import tagMSG

from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from requests import post

from .forms import PostForm
from .models import Post


def home(request , tag=None):
    tag_obj = None
    if not tag:
       posts=Post.objects.all()
    else:
        tag_obj = get_object_or_404(tagMSG , slug=tag)
        posts = Post.objects.filter(tags__in=[tag_obj])
    paginator = Paginator(posts , 5)
    page = request.GET.get('page' , 1)
    posts = paginator.get_page(page)

    return render(request , 'home.html' ,
                {'section' : 'home',
                 'posts': post,
                 })

def detail(request , slug=None):
    post = get_object_or_404(Post , slug=slug)
    return render(request , 'blog/detail.html' , 
                   {
                      'section': 'blog_detail',
                      'post':post,
                   })
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST , request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('home')
    else:
        form = PostForm()
    return render(request , 'blog/create.html',{'section': 'blog_create' , 'form' : form}) 
def edit(request , pk=None):
    post = get_object_or_404(Post , pk=pk)
    if request.method == 'post':
        form = PostForm(request.POST ,request.FILES , instance=post)
        if form.is_valid():
            form.save()
            return redirect("blog:detail" , slug=post.slug)
        else:
            form = PostForm(instance=post)
        return render(request , 'blog/edit.html' ,
                      {'section' : 'blog_edit' ,
                       'form':form,
                       'post': post,   
                      })    

django-project/blog/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="/css/base.css" />
    <title>site</title>
  </head>
  <body>
    <header>
      <ul class="menu">
        <li>
          <a
            class="{% if section == 'home' %}active{% endif %}"
            href="{% url 'home' %}">HOME</a>
        </li>

        <li>
          <a
            class="{% if section == 'blog_create' %}active{% endif %}"
            href="{% url 'blog:create' %}">Add new post</a>
        </li>

        <li>
          {% if not user.is_authenticated %}
          <a href="{% url 'account_login' %}">Sign in</a>
          {% else %}
          <a href="{% url 'account_logout' %}">Sign out</a>
          {% endif %}
        </li>
      </ul>
      {% block content %} some default content{% endblock %}
      <script src="" async defer></script>
    </header>
  </body>
</html>

django-project/blog/templates/blog/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
        {% extends "base.html" %}
        {% block title %}<h1>add new post</h1>{% endblock %}
        {% block content %}

        <form action = "{% url 'blog:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button" type="submit">Create</button>
        </form>

        {% endblock %}
    
    </body>
</html>

django-project/blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
        {% extends "base.html" %}
        {% block title %}{{ post }}{% endblock %}
        {% block content %}

        {% if post.image %}
        <img class="post-img" src="{{ post.image.url }}">
        {% endif %}

        <p>Posted {{ post.date|date:"M J , Y" }}    </p>
        <p>Updated {{ post.updated}}</p>
        {% if post.author %}<p>{{ post.author}}</p>{% endif %}
        <p>{{ post.body }}</p>

        {% endblock %}
    
    </body>
</html>

django-project/blog/templates/blog/edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>

        <form action = "{% url 'blog:edit' post.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button" type="submit">update</button>
        </form>
    
    </body>
</html>

django-project/blog/templates/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
        {% extends "base.html" %}
        {% block content %}
        {% include 'pagination.html' with items=posts %}
        {% for post in posts %}
        {{ post.pk }} : {{ post }} 
        <a href="{{ post.get_absolute_url }}"> {{ post.pk }} : {{ post }}</a><br>
        {% endfor %}
        {% endblock %}
    </body>
</html>

django-project/blog/templates/pagination.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
        <div class="pagination">
            {% if posts.has_previous %}
               <a href="?page=1">First</a>
               <a href="?page={{ posts.previous_page_number}}">previous</a>
               {% endif %}
               
               <span>{{ posts.number }}</span>
               <sapan>of</sapan>
               <span>{{ posts.paginator.num_pages }}</span>

               {% if posts.has_next %}
               <a href="?page={{ posts.next_page_number }}">Next</a>
               <a href="?page={{ posts.paginator.num_pages }}">Last</a>
               {% endif %}

        </div>
    
    </body>
</html>